### ISSUE TITLE
Unexpected encoding of characters

### ISSUE THREAD

**Issue by nu0l** [carl1l/f403#2]
<img width="880" alt="image" src="https://user-images.githubusercontent.com/54735907/196648594-2e95759e-2a27-40b2-8ad5-e778c2bb4cbb.png">
测试过程中，发现“#”会被URL编码，导致bypass403失败

```
  mid_path: #like http://www.baidu.com/abc/ --->    http://www.baidu.com/mid_dpath/abc/
    - "#/.."
```

**Comment by carl1l** [comment]
已修复,师傅可以再测试一下

**Comment by carl1l** [comment]
该bug已修复，师傅可以再测试一下

**Comment by nu0l** [comment]
> 该bug已修复，师傅可以再测试一下

似乎还是有问题。

**Comment by nu0l** [comment]
> 该bug已修复，师傅可以再测试一下

似乎还是有问题，fmt.Println输出正常“#”，程序发包实际为根目录"/"

.yaml
```
http:
  allow_methods:
    - GET
  headers:
    - Client-IP
  end_path: 
    - "?"
  mid_path: 
    - "#/.."
```

这是程序发的包
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/54735907/196831994-796ca2d7-5ac3-46a0-aebf-c4b268ba87dd.png">

这是手工发的包
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/54735907/196832081-25370019-1dd4-40ca-a8b3-251b4748ace6.png">
